// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShoeRetail.Infrastructure.Persistence;

#nullable disable

namespace ShoeRetail.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260823205228_InitialCreate_StoreProfile")]
    partial class InitialCreate_StoreProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShoeRetail.Domain.StoreProfile", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("TRY")
                        .HasColumnName("currency_code");

                    b.Property<int>("DefaultLowStockThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("default_low_stock_threshold");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<short>("StockCodeDigits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)6)
                        .HasColumnName("stock_code_digits");

                    b.Property<string>("StockCodePrefix")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasDefaultValue("GND")
                        .HasColumnName("stock_code_prefix");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("store_name");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_number");

                    b.Property<string>("TaxOffice")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tax_office");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_store_profile");

                    b.ToTable("store_profile", null, t =>
                        {
                            t.HasCheckConstraint("chk_store_profile_currency_format", "currency_code ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("chk_store_profile_low_stock_nonneg", "default_low_stock_threshold >= 0");

                            t.HasCheckConstraint("chk_store_profile_name_not_blank", "btrim(store_name) <> ''");

                            t.HasCheckConstraint("chk_store_profile_singleton", "id = 1");

                            t.HasCheckConstraint("chk_store_profile_stock_digits_range", "stock_code_digits BETWEEN 4 AND 8");

                            t.HasCheckConstraint("chk_store_profile_stock_prefix_format", "stock_code_prefix ~ '^[A-Z]{2,5}$'");
                        });

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            CurrencyCode = "TRY",
                            DefaultLowStockThreshold = 5,
                            StockCodeDigits = (short)6,
                            StockCodePrefix = "GND",
                            StoreName = "Mağaza Adı",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
