-- ============================================================
-- ShoeRetail — Gelişen Şema Scripti (schema.sql)
-- Bu dosya, docs/database/02-physical-blueprint.md ile PARALEL
-- büyütülecek. Blueprint = gerekçeli anlatı, bu dosya = çalıştırılabilir DDL.
--
-- Tamamlanan tablolar: customers, users, products, product_variants
--
-- ÖNEMLİ: Sıra rastgele değil, FK bağımlılıklarına göre dizilmiştir:
--   customers  (bağımsız)
--   users      (customers'a FK verir)
--   products   (bağımsız)
--   product_variants (products'a FK verir)
-- ============================================================


-- ─────────────────────────────
-- 1) customers
-- ─────────────────────────────
CREATE TABLE customers (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_type     varchar(20)   NOT NULL,
    full_name         varchar(200)  NULL,
    company_name      varchar(200)  NULL,
    contact_person    varchar(200)  NULL,
    phone             varchar(30)   NOT NULL,
    email             varchar(255)  NULL,
    tax_number        varchar(50)   NULL,
    tax_office        varchar(100)  NULL,
    billing_address   text          NULL,
    delivery_address  text          NULL,
    notes             text          NULL,
    is_active         boolean       NOT NULL DEFAULT true,
    created_at        timestamptz   NOT NULL DEFAULT now(),
    updated_at        timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT chk_customers_type
        CHECK (customer_type IN ('Individual', 'Corporate')),
    CONSTRAINT chk_customers_type_name_consistency
        CHECK (
            (customer_type = 'Individual' AND full_name    IS NOT NULL) OR
            (customer_type = 'Corporate'  AND company_name IS NOT NULL)
        ),
    CONSTRAINT chk_customers_phone_not_blank
        CHECK (btrim(phone) <> '')
);

CREATE INDEX ix_customers_phone         ON customers (phone);
CREATE INDEX ix_customers_full_name     ON customers (full_name);
CREATE INDEX ix_customers_company_name  ON customers (company_name);


-- ─────────────────────────────
-- 2) users
-- ─────────────────────────────
CREATE TABLE users (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username              varchar(100)  NOT NULL,
    normalized_username   varchar(100)  NOT NULL,
    password_hash         text          NOT NULL,
    role                  varchar(20)   NOT NULL,
    customer_id           bigint        NULL,
    is_active             boolean       NOT NULL DEFAULT true,
    created_at            timestamptz   NOT NULL DEFAULT now(),
    updated_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_users_customer
        FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT,
    CONSTRAINT chk_users_role
        CHECK (role IN ('Seller', 'Customer')),
    CONSTRAINT chk_users_role_customer_consistency
        CHECK (
            (role = 'Seller'   AND customer_id IS NULL) OR
            (role = 'Customer' AND customer_id IS NOT NULL)
        )
);

CREATE UNIQUE INDEX ux_users_normalized_username ON users (normalized_username);
CREATE INDEX ix_users_customer_id ON users (customer_id);


-- ─────────────────────────────
-- 3) products
-- ─────────────────────────────
CREATE TABLE products (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          varchar(200)  NOT NULL,
    brand         varchar(100)  NULL,
    model         varchar(100)  NULL,
    category      varchar(100)  NULL,
    material      varchar(100)  NULL,
    description   text          NULL,
    is_active     boolean       NOT NULL DEFAULT true,
    created_at    timestamptz   NOT NULL DEFAULT now(),
    updated_at    timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT chk_products_name_not_blank
        CHECK (btrim(name) <> '')
);

CREATE INDEX ix_products_name   ON products (name);
CREATE INDEX ix_products_brand  ON products (brand);


-- ─────────────────────────────
-- 4) product_variants
-- ─────────────────────────────
CREATE TABLE product_variants (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       bigint        NOT NULL,
    size             varchar(20)   NOT NULL,
    color            varchar(50)   NOT NULL,
    sku              varchar(50)   NOT NULL,
    barcode          varchar(50)   NULL,
    purchase_price   numeric(18,2) NOT NULL,
    sale_price       numeric(18,2) NOT NULL,
    is_active        boolean       NOT NULL DEFAULT true,
    created_at       timestamptz   NOT NULL DEFAULT now(),
    updated_at       timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_product_variants_product
        FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,
    CONSTRAINT chk_product_variants_size_not_blank
        CHECK (btrim(size) <> ''),
    CONSTRAINT chk_product_variants_color_not_blank
        CHECK (btrim(color) <> ''),
    CONSTRAINT chk_product_variants_sku_not_blank
        CHECK (btrim(sku) <> ''),
    CONSTRAINT chk_product_variants_purchase_price_nonneg
        CHECK (purchase_price >= 0),
    CONSTRAINT chk_product_variants_sale_price_nonneg
        CHECK (sale_price >= 0)
);

CREATE UNIQUE INDEX ux_product_variants_sku
    ON product_variants (sku);
CREATE UNIQUE INDEX ux_product_variants_barcode
    ON product_variants (barcode) WHERE barcode IS NOT NULL;
CREATE UNIQUE INDEX ux_product_variants_product_size_color
    ON product_variants (product_id, size, color);
CREATE INDEX ix_product_variants_product_id
    ON product_variants (product_id);


-- ─────────────────────────────
-- 5) inventory
-- ─────────────────────────────
CREATE TABLE inventory (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_variant_id    bigint        NOT NULL,
    quantity_on_hand      integer       NOT NULL DEFAULT 0,
    quantity_reserved     integer       NOT NULL DEFAULT 0,
    quantity_available    integer       GENERATED ALWAYS AS (quantity_on_hand - quantity_reserved) STORED,
    created_at            timestamptz   NOT NULL DEFAULT now(),
    updated_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_inventory_product_variant
        FOREIGN KEY (product_variant_id) REFERENCES product_variants(id) ON DELETE RESTRICT,
    CONSTRAINT chk_inventory_on_hand_nonneg
        CHECK (quantity_on_hand >= 0),
    CONSTRAINT chk_inventory_reserved_nonneg
        CHECK (quantity_reserved >= 0),
    CONSTRAINT chk_inventory_reserved_le_on_hand
        CHECK (quantity_reserved <= quantity_on_hand)
);

CREATE UNIQUE INDEX ux_inventory_product_variant_id
    ON inventory (product_variant_id);