-- ============================================================
--  ShoeRetail — Veritabanı Şeması
--  Hedef: PostgreSQL
--
--  Bu dosya, docs/database/02-physical-blueprint.md ile PARALEL büyür.
--    Blueprint = gerekçeli anlatı (NEDEN)
--    Bu dosya  = çalıştırılabilir DDL (NE)
--
--  Pivot notu: bu dosya sıfırdan yazılmıştır. Pivot öncesi 16 tablolu sürüm
--  archive/v1-schema.sql içindedir ve GEÇERSİZDİR.
--
--  Tablo sırası rastgele değil, FK bağımlılıklarına göre dizilmiştir.
--  Sıra için blueprint'teki "Tablo Sırası ve Bağımlılıklar" bölümüne bakınız.
--
--  Durum: 22/22 tablo — TAMAMLANDI
-- ============================================================


-- ─────────────────────────────
-- 1) store_profile
--    Tek satırlık işletme yapılandırması.
--    PK istisnası: bu bir varlık koleksiyonu değil, tekil yapılandırma kaydı.
-- ─────────────────────────────
CREATE TABLE store_profile (
    id                    smallint      PRIMARY KEY DEFAULT 1,

    -- İşletme kimliği (yazdırılan belgelerde kullanılır)
    store_name            varchar(200)  NOT NULL,
    phone                 varchar(30)   NULL,
    email                 varchar(255)  NULL,
    address               text          NULL,
    tax_number            varchar(50)   NULL,
    tax_office            varchar(100)  NULL,

    -- Para birimi (ISO 4217)
    currency_code         char(3)       NOT NULL DEFAULT 'TRY',

    -- Stok kodu üretim kuralı (white-label: koda gömülemez)
    stock_code_prefix     varchar(5)    NOT NULL DEFAULT 'GND',
    stock_code_digits     smallint      NOT NULL DEFAULT 6,

    -- Yeni varyantlara uygulanacak kritik stok varsayılanı
    default_low_stock_threshold  integer NOT NULL DEFAULT 5,

    updated_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT chk_store_profile_singleton
        CHECK (id = 1),

    CONSTRAINT chk_store_profile_name_not_blank
        CHECK (btrim(store_name) <> ''),

    CONSTRAINT chk_store_profile_currency_format
        CHECK (currency_code ~ '^[A-Z]{3}$'),

    CONSTRAINT chk_store_profile_stock_prefix_format
        CHECK (stock_code_prefix ~ '^[A-Z]{2,5}$'),

    CONSTRAINT chk_store_profile_stock_digits_range
        CHECK (stock_code_digits BETWEEN 4 AND 8),

    CONSTRAINT chk_store_profile_low_stock_nonneg
        CHECK (default_low_stock_threshold >= 0)
);

-- Kurulumda otomatik oluşan tek satır
INSERT INTO store_profile (store_name) VALUES ('Mağaza Adı');


-- ─────────────────────────────
-- 2) customers
--    Perakendeci müşteriler. Sisteme GİRİŞ YAPMAZLAR — sadece veri kaydıdır.
-- ─────────────────────────────
CREATE TABLE customers (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    customer_type     varchar(20)   NOT NULL,

    -- Tipe bağlı kimlik alanları
    full_name         varchar(200)  NULL,   -- Individual için zorunlu
    company_name      varchar(200)  NULL,   -- Corporate için zorunlu
    contact_person    varchar(200)  NULL,

    -- İletişim
    phone             varchar(30)   NOT NULL,
    email             varchar(255)  NULL,

    -- Vergi bilgisi
    tax_number        varchar(50)   NULL,
    tax_office        varchar(100)  NULL,

    -- Adres
    city              varchar(100)  NULL,
    district          varchar(100)  NULL,
    billing_address   text          NULL,
    delivery_address  text          NULL,

    -- Ticari koşullar
    default_payment_term_days  smallint       NULL,
    credit_limit               numeric(18,2)  NULL,

    notes             text          NULL,

    is_active         boolean       NOT NULL DEFAULT true,
    created_at        timestamptz   NOT NULL DEFAULT now(),
    updated_at        timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT chk_customers_type
        CHECK (customer_type IN ('Individual', 'Corporate')),

    CONSTRAINT chk_customers_type_name_consistency
        CHECK (
            (customer_type = 'Individual' AND full_name    IS NOT NULL) OR
            (customer_type = 'Corporate'  AND company_name IS NOT NULL)
        ),

    CONSTRAINT chk_customers_phone_not_blank
        CHECK (btrim(phone) <> ''),

    CONSTRAINT chk_customers_payment_term_nonneg
        CHECK (default_payment_term_days IS NULL OR default_payment_term_days >= 0),

    -- NOT: credit_limit yalnızca >= 0 olmalı. Limit AŞIMI burada engellenmez;
    -- Application katmanı uyarır, kullanıcı onaylarsa işlem devam eder.
    CONSTRAINT chk_customers_credit_limit_nonneg
        CHECK (credit_limit IS NULL OR credit_limit >= 0)
);

CREATE INDEX ix_customers_phone         ON customers (phone);
CREATE INDEX ix_customers_full_name     ON customers (full_name);
CREATE INDEX ix_customers_company_name  ON customers (company_name);
CREATE INDEX ix_customers_city          ON customers (city);


-- ─────────────────────────────
-- 3) suppliers
--    Üreticiler. Sisteme GİRİŞ YAPARLAR (users.supplier_id buraya FK verir).
--    customers'tan farklı olarak tip ayrımı yok: üretici her zaman firmadır.
-- ─────────────────────────────
CREATE TABLE suppliers (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Kimlik
    company_name      varchar(200)  NOT NULL,
    contact_person    varchar(200)  NULL,

    -- İletişim
    phone             varchar(30)   NOT NULL,
    email             varchar(255)  NULL,

    -- Vergi bilgisi
    tax_number        varchar(50)   NULL,
    tax_office        varchar(100)  NULL,

    -- Adres
    city              varchar(100)  NULL,
    district          varchar(100)  NULL,
    address           text          NULL,

    -- Ticari koşullar
    default_payment_term_days  smallint  NULL,   -- borcumuzun vadesi (gün)
    default_lead_time_days     smallint  NULL,   -- ortalama termin süresi (gün)

    notes             text          NULL,

    is_active         boolean       NOT NULL DEFAULT true,
    created_at        timestamptz   NOT NULL DEFAULT now(),
    updated_at        timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT chk_suppliers_company_name_not_blank
        CHECK (btrim(company_name) <> ''),

    CONSTRAINT chk_suppliers_phone_not_blank
        CHECK (btrim(phone) <> ''),

    CONSTRAINT chk_suppliers_payment_term_nonneg
        CHECK (default_payment_term_days IS NULL OR default_payment_term_days >= 0),

    CONSTRAINT chk_suppliers_lead_time_nonneg
        CHECK (default_lead_time_days IS NULL OR default_lead_time_days >= 0)
);

CREATE INDEX ix_suppliers_company_name ON suppliers (company_name);
CREATE INDEX ix_suppliers_phone        ON suppliers (phone);


-- ─────────────────────────────
-- 4) users
--    Giriş yapan kimlikler. İki rol: Owner (biz) ve Manufacturer (üretici).
--    Perakendeci müşterilerin kullanıcı hesabı YOKTUR.
--
--    username ASCII ile sınırlıdır: Türkçe 'I/ı/İ/i' dönüşümü kültüre bağlıdır
--    ve normalize edilmiş kullanıcı adını bozar. C# tarafında ToUpperInvariant().
-- ─────────────────────────────
CREATE TABLE users (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Kimlik doğrulama
    username              varchar(100)  NOT NULL,
    normalized_username   varchar(100)  NOT NULL,   -- ToUpperInvariant()
    password_hash         text          NOT NULL,

    -- Görüntüleme (audit/history ekranlarında insan-okunur isim)
    full_name             varchar(200)  NOT NULL,

    -- Yetkilendirme
    role                  varchar(20)   NOT NULL,
    supplier_id           bigint        NULL,       -- Manufacturer ise zorunlu

    -- Operasyonel bilgi
    last_login_at         timestamptz   NULL,

    is_active             boolean       NOT NULL DEFAULT true,
    created_at            timestamptz   NOT NULL DEFAULT now(),
    updated_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_users_supplier
        FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,

    CONSTRAINT chk_users_role
        CHECK (role IN ('Owner', 'Manufacturer')),

    -- GÜVENLİK KRİTİK: supplier_id'siz bir Manufacturer, RBAC filtresini çökertir
    -- ve potansiyel olarak TÜM siparişleri görebilir.
    CONSTRAINT chk_users_role_supplier_consistency
        CHECK (
            (role = 'Owner'        AND supplier_id IS NULL) OR
            (role = 'Manufacturer' AND supplier_id IS NOT NULL)
        ),

    CONSTRAINT chk_users_username_format
        CHECK (username ~ '^[A-Za-z0-9._-]{3,50}$'),

    CONSTRAINT chk_users_normalized_username_format
        CHECK (normalized_username ~ '^[A-Z0-9._-]{3,50}$'),

    CONSTRAINT chk_users_full_name_not_blank
        CHECK (btrim(full_name) <> '')
);

CREATE UNIQUE INDEX ux_users_normalized_username ON users (normalized_username);
CREATE INDEX ix_users_supplier_id ON users (supplier_id);


-- ─────────────────────────────
-- 5) products
--    Ürün MODELİ. Beden/renk kırılımı product_variants'ta.
--    Stok kodu (GND000142) burada yaşar — modeli tanımlar, varyantı değil.
--
--    CHECK yalnızca GENEL ŞEKLİ doğrular; bu kurulumun asıl kuralı
--    (önek 'GND', hane 6) store_profile'dan okunur. Şema tüm kurulumlarda aynıdır.
-- ─────────────────────────────
CREATE TABLE products (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    stock_code            varchar(15)   NOT NULL,

    name                  varchar(200)  NOT NULL,
    brand                 varchar(100)  NULL,
    model                 varchar(100)  NULL,
    category              varchar(100)  NULL,
    material              varchar(100)  NULL,
    gender                varchar(20)   NULL,
    season                varchar(20)   NULL,
    description           text          NULL,

    -- Varsayılan üretici: KISIT DEĞİL, İPUCU.
    -- Bir alışın gerçek üreticisi purchase_orders.supplier_id'dir.
    supplier_id           bigint        NULL,
    supplier_product_code varchar(100)  NULL,

    is_active             boolean       NOT NULL DEFAULT true,
    created_at            timestamptz   NOT NULL DEFAULT now(),
    updated_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_products_supplier
        FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,

    CONSTRAINT chk_products_stock_code_format
        CHECK (stock_code ~ '^[A-Z]{2,5}[0-9]{4,8}$'),

    CONSTRAINT chk_products_name_not_blank
        CHECK (btrim(name) <> ''),

    CONSTRAINT chk_products_gender
        CHECK (gender IS NULL OR gender IN ('Men', 'Women', 'Kids', 'Unisex')),

    CONSTRAINT chk_products_season
        CHECK (season IS NULL OR season IN ('Summer', 'Winter', 'AllSeason'))
);

CREATE UNIQUE INDEX ux_products_stock_code ON products (stock_code);
CREATE INDEX ix_products_name        ON products (name);
CREATE INDEX ix_products_brand       ON products (brand);
CREATE INDEX ix_products_supplier_id ON products (supplier_id);
CREATE INDEX ix_products_gender      ON products (gender);
CREATE INDEX ix_products_season      ON products (season);


-- ─────────────────────────────
-- 6) product_variants
--    Bir modelin beden+renk kırılımı. Stoğun ve fiyatın gerçek taşıyıcısı.
--
--    SKU SAKLANMAZ: stock_code + size + color'dan türetilebilir, dolayısıyla
--    tek doğruluk kaynağı ilkesi gereği kolon olarak tutulmaz. Görüntülenecek
--    kod Application katmanında üretilir.
--
--    color, uygulama tarafından normalize edilmiş (ToUpperInvariant) olarak
--    saklanır — çünkü UNIQUE kısıtının parçasıdır ve 'Siyah'/'siyah' ikiliği
--    stoğu ikiye böler. DB'de upper() KULLANILMAZ: Türkçe 'i' dönüşümü
--    veritabanının dil ayarına bağlıdır ve sunucu taşınınca bozulur.
-- ─────────────────────────────
CREATE TABLE product_variants (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       bigint        NOT NULL,

    size             varchar(20)   NOT NULL,
    color            varchar(50)   NOT NULL,

    barcode          varchar(50)   NULL,

    purchase_price   numeric(18,2) NOT NULL,
    sale_price       numeric(18,2) NOT NULL,

    is_active        boolean       NOT NULL DEFAULT true,
    created_at       timestamptz   NOT NULL DEFAULT now(),
    updated_at       timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_product_variants_product
        FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT,

    -- '41' ile '41 ' farklı metinlerdir ve UNIQUE index bunları ayrı sayar
    -- → görünmez mükerrer varyant. Baştaki/sondaki boşluk kökten yasaklanır.
    CONSTRAINT chk_product_variants_size_trimmed
        CHECK (size = btrim(size) AND size <> ''),

    CONSTRAINT chk_product_variants_color_trimmed
        CHECK (color = btrim(color) AND color <> ''),

    CONSTRAINT chk_product_variants_purchase_price_nonneg
        CHECK (purchase_price >= 0),

    CONSTRAINT chk_product_variants_sale_price_nonneg
        CHECK (sale_price >= 0)
);

-- Varyantın gerçek kimliği: model + beden + renk
CREATE UNIQUE INDEX ux_product_variants_product_size_color
    ON product_variants (product_id, size, color);

-- Barkod opsiyonel ama girildiğinde benzersiz
CREATE UNIQUE INDEX ux_product_variants_barcode
    ON product_variants (barcode) WHERE barcode IS NOT NULL;

CREATE INDEX ix_product_variants_product_id
    ON product_variants (product_id);


-- ─────────────────────────────
-- 7) inventory
--    Varyant başına ANLIK stok bakiyesi. Hareket geçmişi ayrı tabloda
--    (inventory_movements) tutulur — "bakiye + defter" deseni.
--
--    Ayrı tablo olmasının asıl sebebi kilitleme: stok satırı FOR UPDATE ile
--    kilitlendiğinde ürün bilgisi okumaları bloke olmaz.
-- ─────────────────────────────
CREATE TABLE inventory (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_variant_id    bigint        NOT NULL,

    quantity_on_hand      integer       NOT NULL DEFAULT 0,
    quantity_reserved     integer       NOT NULL DEFAULT 0,
    quantity_available    integer       GENERATED ALWAYS AS
                                        (quantity_on_hand - quantity_reserved) STORED,

    -- DEFAULT başka tablodan okuyamaz; Application katmanı yeni varyantta
    -- store_profile.default_low_stock_threshold değerini buraya yazar.
    low_stock_threshold   integer       NOT NULL DEFAULT 0,

    created_at            timestamptz   NOT NULL DEFAULT now(),
    updated_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_inventory_product_variant
        FOREIGN KEY (product_variant_id) REFERENCES product_variants(id) ON DELETE RESTRICT,

    CONSTRAINT chk_inventory_on_hand_nonneg
        CHECK (quantity_on_hand >= 0),

    CONSTRAINT chk_inventory_reserved_nonneg
        CHECK (quantity_reserved >= 0),

    -- "Elinde olmayanı söz veremezsin"
    CONSTRAINT chk_inventory_reserved_le_on_hand
        CHECK (quantity_reserved <= quantity_on_hand),

    CONSTRAINT chk_inventory_low_stock_nonneg
        CHECK (low_stock_threshold >= 0)
);

-- 1:1 ilişki: her varyantın tam bir stok satırı olur
CREATE UNIQUE INDEX ux_inventory_product_variant_id
    ON inventory (product_variant_id);


-- ─────────────────────────────
-- 8) orders
--    Perakendeciye satış siparişi. ONAY ADIMI YOKTUR — siparişi kendi
--    personelimiz girer. Fiziksel stok SEVKİYATTA düşer, borç da orada yazılır.
-- ─────────────────────────────

-- Sipariş numarası üreteci. Yıl başında sıfırlanmaz: yıl+sıra çiftini birlikte
-- kilitlemek yarış durumu doğurur; sürekli akan bir sequence kilitsiz garantidir.
-- Boşluklar (geri alınan işlemlerde yanan numaralar) normaldir — numara kesintisiz
-- olmak zorunda değil, benzersiz olmak zorunda.
CREATE SEQUENCE order_number_seq;

CREATE TABLE orders (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_number          varchar(30)   NOT NULL,   -- SIP-2026-000142
    customer_id           bigint        NOT NULL,
    created_by_user_id    bigint        NOT NULL,

    -- order_date = siparişin ALINDIĞI gün (created_at = kaydın girildiği an).
    -- "Dün telefonda aldığım siparişi bugün giriyorum" senaryosu için ayrıdır.
    order_date            date          NOT NULL DEFAULT CURRENT_DATE,
    expected_ship_date    date          NULL,

    status                varchar(20)   NOT NULL DEFAULT 'Received',

    total_amount          numeric(18,2) NOT NULL DEFAULT 0,

    delivery_address      text          NULL,       -- snapshot (müşteriden kopyalanır)
    notes                 text          NULL,

    -- Durum geçiş damgaları
    shipped_at            timestamptz   NULL,
    shipped_by_user_id    bigint        NULL,
    delivered_at          timestamptz   NULL,
    cancelled_at          timestamptz   NULL,
    cancelled_by_user_id  bigint        NULL,
    cancellation_reason   text          NULL,

    created_at            timestamptz   NOT NULL DEFAULT now(),
    updated_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_orders_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_orders_shipped_by
        FOREIGN KEY (shipped_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_orders_cancelled_by
        FOREIGN KEY (cancelled_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,

    CONSTRAINT chk_orders_status
        CHECK (status IN ('Received','Preparing','Shipped','Delivered','Cancelled')),

    CONSTRAINT chk_orders_total_nonneg
        CHECK (total_amount >= 0),

    CONSTRAINT chk_orders_shipped_fields
        CHECK (
            status NOT IN ('Shipped','Delivered')
            OR (shipped_at IS NOT NULL AND shipped_by_user_id IS NOT NULL)
        ),

    CONSTRAINT chk_orders_delivered_fields
        CHECK (
            status <> 'Delivered' OR delivered_at IS NOT NULL
        ),

    -- IS NOT NULL kontrolü ŞART: btrim(NULL) <> '' ifadesi NULL döner ve
    -- CHECK kısıtı NULL sonucu GEÇERLİ sayar → gerekçesiz iptal sızardı.
    CONSTRAINT chk_orders_cancelled_fields
        CHECK (
            status <> 'Cancelled'
            OR (cancelled_at IS NOT NULL
                AND cancelled_by_user_id IS NOT NULL
                AND cancellation_reason IS NOT NULL
                AND btrim(cancellation_reason) <> '')
        )
);

CREATE UNIQUE INDEX ux_orders_order_number ON orders (order_number);
CREATE INDEX ix_orders_customer_id        ON orders (customer_id);
CREATE INDEX ix_orders_status             ON orders (status);
CREATE INDEX ix_orders_order_date         ON orders (order_date);
CREATE INDEX ix_orders_created_by_user_id ON orders (created_by_user_id);


-- ─────────────────────────────
-- 9) order_items
--    Sipariş kalemi. Ürün bilgisini SNAPSHOT olarak saklar (Değişmez Kural #5):
--    ürün adı/fiyatı sonradan değişse bile geçmiş sipariş değişmez.
--
--    Kalem silme: yalnızca sipariş Received/Preparing durumundayken serbesttir.
--    Shipped/Delivered/Cancelled sonrası ASLA silinmez (Application katmanı zorlar).
-- ─────────────────────────────
CREATE TABLE order_items (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id              bigint        NOT NULL,
    product_variant_id    bigint        NOT NULL,   -- izleme/raporlama için

    -- SNAPSHOT alanları (sipariş anındaki hâl)
    stock_code_snapshot   varchar(15)   NOT NULL,
    product_name_snapshot varchar(200)  NOT NULL,
    size_snapshot         varchar(20)   NOT NULL,
    color_snapshot        varchar(50)   NOT NULL,

    quantity              integer       NOT NULL,
    unit_sale_price       numeric(18,2) NOT NULL,
    unit_purchase_price   numeric(18,2) NOT NULL,   -- SADECE Owner görür

    line_total            numeric(18,2) GENERATED ALWAYS AS
                          (quantity * unit_sale_price) STORED,

    created_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
    CONSTRAINT fk_order_items_product_variant
        FOREIGN KEY (product_variant_id) REFERENCES product_variants(id) ON DELETE RESTRICT,

    CONSTRAINT chk_order_items_quantity_positive
        CHECK (quantity > 0),

    CONSTRAINT chk_order_items_sale_price_nonneg
        CHECK (unit_sale_price >= 0),

    CONSTRAINT chk_order_items_purchase_price_nonneg
        CHECK (unit_purchase_price >= 0),

    CONSTRAINT chk_order_items_snapshots_not_blank
        CHECK (
            btrim(stock_code_snapshot)   <> '' AND
            btrim(product_name_snapshot) <> '' AND
            btrim(size_snapshot)         <> '' AND
            btrim(color_snapshot)        <> ''
        )
);

-- Aynı siparişte aynı varyant tek satır olabilir (UI adetleri birleştirir)
CREATE UNIQUE INDEX ux_order_items_order_variant
    ON order_items (order_id, product_variant_id);

CREATE INDEX ix_order_items_order_id
    ON order_items (order_id);
CREATE INDEX ix_order_items_product_variant_id
    ON order_items (product_variant_id);


-- ─────────────────────────────
-- 10) order_history
--     Siparişin iş odaklı zaman çizelgesi — kullanıcının sipariş detayında
--     gördüğü okunabilir geçmiş. audit_logs'tan farkı: dar kapsam, insan dili,
--     hazır biçimlendirilmiş metin.
--     APPEND-ONLY: güncellenmez, silinmez (bu yüzden updated_at yok).
-- ─────────────────────────────
CREATE TABLE order_history (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id              bigint        NOT NULL,

    event_type            varchar(30)   NOT NULL,
    old_value             text          NULL,
    new_value             text          NULL,
    note                  text          NULL,

    changed_by_user_id    bigint        NOT NULL,
    changed_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_order_history_order
        FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
    CONSTRAINT fk_order_history_changed_by
        FOREIGN KEY (changed_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,

    CONSTRAINT chk_order_history_event_type
        CHECK (event_type IN (
            'Created',
            'StatusChanged',
            'ItemAdded',
            'ItemChanged',
            'ItemRemoved',
            'NoteChanged',
            'ExpectedShipDateChanged',
            'DeliveryAddressChanged'
        ))
);

-- Bileşik index: WHERE order_id = ? ORDER BY changed_at sorgusunun tam karşılığı.
-- Hem filtreyi hem sıralamayı karşılar; DB ayrıca sıralama yapmaz.
CREATE INDEX ix_order_history_order_id_changed_at
    ON order_history (order_id, changed_at);

CREATE INDEX ix_order_history_changed_by_user_id
    ON order_history (changed_by_user_id);


-- ─────────────────────────────
-- 11) purchase_orders
--     Üreticiye verdiğimiz sipariş. ÜRETİCİNİN GÖRDÜĞÜ TEK VERİ.
--
--     GİZLİLİK: her üretici sorgusu WHERE supplier_id = <kendi id'si>
--     ile filtrelenir VE status <> 'Draft' koşulu eklenir.
--
--     Teslim durumu (Beklemede/Kısmi/Tamamlandı) SAKLANMAZ — kalemlerdeki
--     ordered_quantity vs received_quantity karşılaştırmasından türetilir.
--     'Completed' bundan farklıdır: "kalanı gelmeyecek, kapat" iş kararıdır.
-- ─────────────────────────────

CREATE SEQUENCE purchase_order_number_seq;   -- ALS = ALIŞ

CREATE TABLE purchase_orders (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    purchase_order_number    varchar(30)   NOT NULL,   -- ALS-2026-000042
    supplier_id              bigint        NOT NULL,
    created_by_user_id       bigint        NOT NULL,

    order_date               date          NOT NULL DEFAULT CURRENT_DATE,
    expected_delivery_date   date          NULL,       -- supplier.default_lead_time_days'ten
    payment_due_date         date          NULL,       -- MAL KABULDE hesaplanır (vade maldan başlar)

    status                   varchar(20)   NOT NULL DEFAULT 'Draft',

    total_amount             numeric(18,2) NOT NULL DEFAULT 0,

    supplier_reference       varchar(100)  NULL,       -- üreticinin kendi sipariş no'su
    notes                    text          NULL,       -- ÜRETİCİ DE GÖRÜR (ona mesaj)
    internal_notes           text          NULL,       -- SADECE BİZ (asla DTO'ya girmez)

    -- Durum geçiş damgaları
    sent_at                  timestamptz   NULL,
    supplier_shipped_at      timestamptz   NULL,
    completed_at             timestamptz   NULL,
    completed_by_user_id     bigint        NULL,
    cancelled_at             timestamptz   NULL,
    cancelled_by_user_id     bigint        NULL,
    cancellation_reason      text          NULL,

    created_at               timestamptz   NOT NULL DEFAULT now(),
    updated_at               timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_purchase_orders_supplier
        FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_orders_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_orders_completed_by
        FOREIGN KEY (completed_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_orders_cancelled_by
        FOREIGN KEY (cancelled_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,

    -- Draft: biz | Sent: biz | InProduction/Ready/Shipped: ÜRETİCİ
    -- Completed: biz | Cancelled: biz
    CONSTRAINT chk_purchase_orders_status
        CHECK (status IN ('Draft','Sent','InProduction','Ready','Shipped','Completed','Cancelled')),

    CONSTRAINT chk_purchase_orders_total_nonneg
        CHECK (total_amount >= 0),

    -- Cancelled istisnadır: sipariş gönderilmeden önce de iptal edilebilir
    CONSTRAINT chk_purchase_orders_sent_fields
        CHECK (
            status IN ('Draft','Cancelled')
            OR sent_at IS NOT NULL
        ),

    CONSTRAINT chk_purchase_orders_completed_fields
        CHECK (
            status <> 'Completed'
            OR (completed_at IS NOT NULL AND completed_by_user_id IS NOT NULL)
        ),

    CONSTRAINT chk_purchase_orders_cancelled_fields
        CHECK (
            status <> 'Cancelled'
            OR (cancelled_at IS NOT NULL
                AND cancelled_by_user_id IS NOT NULL
                AND cancellation_reason IS NOT NULL
                AND btrim(cancellation_reason) <> '')
        )
);

CREATE UNIQUE INDEX ux_purchase_orders_number
    ON purchase_orders (purchase_order_number);

CREATE INDEX ix_purchase_orders_supplier_id       ON purchase_orders (supplier_id);
CREATE INDEX ix_purchase_orders_status            ON purchase_orders (status);
CREATE INDEX ix_purchase_orders_order_date        ON purchase_orders (order_date);
CREATE INDEX ix_purchase_orders_payment_due       ON purchase_orders (payment_due_date);
CREATE INDEX ix_purchase_orders_expected_delivery ON purchase_orders (expected_delivery_date);
CREATE INDEX ix_purchase_orders_created_by        ON purchase_orders (created_by_user_id);


-- ─────────────────────────────
-- 12) purchase_order_items
--     Satın alma sipariş kalemi. order_items'tan farkı: kısmi teslimat için
--     iki miktar (sipariş edilen / teslim alınan) ve iki tutar kolonu.
--
--     FAZLA TESLİMAT BİLİNÇLİ OLARAK ENGELLENMEZ:
--     received > ordered olabilir. Gerçek hayatta üretici fazla gönderebilir;
--     DB engellerse operatör gerçeği kaydedemez ve fazlalık stok dışı kalır.
--     Tercih sırası: stok doğruluğu > sipariş düzeni.
--     Application katmanı uyarır, karar operatörde.
-- ─────────────────────────────
CREATE TABLE purchase_order_items (
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id        bigint        NOT NULL,
    product_variant_id       bigint        NOT NULL,

    -- SNAPSHOT alanları (sipariş anındaki hâl)
    stock_code_snapshot      varchar(15)   NOT NULL,
    product_name_snapshot    varchar(200)  NOT NULL,
    size_snapshot            varchar(20)   NOT NULL,
    color_snapshot           varchar(50)   NOT NULL,
    supplier_product_code    varchar(100)  NULL,      -- üreticinin kendi kodu

    ordered_quantity         integer       NOT NULL,
    received_quantity        integer       NOT NULL DEFAULT 0,   -- birikimli

    unit_purchase_price      numeric(18,2) NOT NULL,

    -- Taahhüt edilen tutar (purchase_orders.total_amount bunların toplamıdır)
    line_total               numeric(18,2) GENERATED ALWAYS AS
                             (ordered_quantity * unit_purchase_price) STORED,
    -- Borçlanılan tutar (gelmeyen malın parası ödenmez)
    received_total           numeric(18,2) GENERATED ALWAYS AS
                             (received_quantity * unit_purchase_price) STORED,

    notes                    text          NULL,

    created_at               timestamptz   NOT NULL DEFAULT now(),
    updated_at               timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_purchase_order_items_order
        FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE RESTRICT,
    CONSTRAINT fk_purchase_order_items_product_variant
        FOREIGN KEY (product_variant_id) REFERENCES product_variants(id) ON DELETE RESTRICT,

    CONSTRAINT chk_purchase_order_items_ordered_positive
        CHECK (ordered_quantity > 0),

    CONSTRAINT chk_purchase_order_items_received_nonneg
        CHECK (received_quantity >= 0),

    CONSTRAINT chk_purchase_order_items_price_nonneg
        CHECK (unit_purchase_price >= 0),

    CONSTRAINT chk_purchase_order_items_snapshots_not_blank
        CHECK (
            btrim(stock_code_snapshot)   <> '' AND
            btrim(product_name_snapshot) <> '' AND
            btrim(size_snapshot)         <> '' AND
            btrim(color_snapshot)        <> ''
        )
);

-- Aynı satın alma siparişinde aynı varyant tek satır
CREATE UNIQUE INDEX ux_purchase_order_items_order_variant
    ON purchase_order_items (purchase_order_id, product_variant_id);

CREATE INDEX ix_purchase_order_items_order_id
    ON purchase_order_items (purchase_order_id);
CREATE INDEX ix_purchase_order_items_product_variant_id
    ON purchase_order_items (product_variant_id);


-- ─────────────────────────────
-- 13) purchase_order_history
--     Satın alma siparişinin zaman çizelgesi. order_history'den farkı:
--     kayıtları HEM BİZ HEM ÜRETİCİ oluşturur (changed_by_user_id ikisinden
--     biri olabilir).
--     APPEND-ONLY: güncellenmez, silinmez.
--
--     GİZLİLİK 1: Üretici yalnızca changed_at >= po.sent_at olan satırları görür
--                 (taslak aşamasındaki adet değişiklikleri gizli kalır).
--     GİZLİLİK 2: Üretici DTO'sunda bizim kullanıcı adlarımız 'Alıcı' olarak
--                 maskelenir; kendi kullanıcıları gerçek adıyla görünür.
--     GİZLİLİK 3: internal_notes değişiklikleri buraya YAZILMAZ — "iç not değişti"
--                 satırı bile bilgi sızıntısıdır. O kayıtlar audit_logs'a gider.
-- ─────────────────────────────
CREATE TABLE purchase_order_history (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_id     bigint        NOT NULL,

    event_type            varchar(30)   NOT NULL,
    old_value             text          NULL,
    new_value             text          NULL,
    note                  text          NULL,

    changed_by_user_id    bigint        NOT NULL,
    changed_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_po_history_purchase_order
        FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE RESTRICT,
    CONSTRAINT fk_po_history_changed_by
        FOREIGN KEY (changed_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,

    CONSTRAINT chk_po_history_event_type
        CHECK (event_type IN (
            'Created',
            'StatusChanged',
            'ItemAdded',
            'ItemChanged',
            'ItemRemoved',
            'GoodsReceived',
            'NoteChanged',
            'ExpectedDeliveryDateChanged',
            'SupplierReferenceChanged'
        ))
);

CREATE INDEX ix_po_history_order_id_changed_at
    ON purchase_order_history (purchase_order_id, changed_at);

CREATE INDEX ix_po_history_changed_by_user_id
    ON purchase_order_history (changed_by_user_id);


-- ─────────────────────────────
-- 14) inventory_movements
--     Stok hareket defteri. inventory "şu an 17 var" der; bu tablo "NEDEN 17?"
--     sorusunu cevaplar. account_transactions'ın stok tarafındaki ikizi.
--     APPEND-ONLY: yanlış hareket düzeltme hareketiyle telafi edilir, satır
--     güncellenmez/silinmez.
--
--     NOT: v1'de bu tablo orders'tan ÖNCE geliyordu ve FK sırası sorunu vardı.
--     Yeni sıralamada orders (8) ve purchase_orders (11) hazır — sorun yapısal
--     olarak ortadan kalktı.
-- ─────────────────────────────
CREATE TABLE inventory_movements (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_variant_id    bigint        NOT NULL,

    movement_type         varchar(30)   NOT NULL,
    on_hand_delta         integer       NOT NULL DEFAULT 0,
    reserved_delta        integer       NOT NULL DEFAULT 0,

    -- Hangi belgeye bağlı (tipine göre biri dolu olur)
    order_id              bigint        NULL,
    purchase_order_id     bigint        NULL,

    reason                text          NULL,

    created_by_user_id    bigint        NOT NULL,
    created_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_inventory_movements_variant
        FOREIGN KEY (product_variant_id) REFERENCES product_variants(id) ON DELETE RESTRICT,
    CONSTRAINT fk_inventory_movements_order
        FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
    CONSTRAINT fk_inventory_movements_purchase_order
        FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE RESTRICT,
    CONSTRAINT fk_inventory_movements_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,

    -- Her tipin işaret imzası. Geçerli tip listesini de zorlar:
    -- listede olmayan bir tip hiçbir dala uymaz ve reddedilir.
    -- 'Sale' için reserved_delta <= 0 (bilinçli olarak gevşek): sıkı kısıt,
    -- rezervasyonu düşmüş bir siparişin sevkiyat transaction'ını patlatırdı.
    CONSTRAINT chk_inventory_movements_type_signature
        CHECK (
            (movement_type = 'InitialStock'        AND on_hand_delta >  0 AND reserved_delta =  0) OR
            (movement_type = 'Purchase'            AND on_hand_delta >  0 AND reserved_delta =  0) OR
            (movement_type = 'Return'              AND on_hand_delta >  0 AND reserved_delta =  0) OR
            (movement_type = 'ManualIncrease'      AND on_hand_delta >  0 AND reserved_delta =  0) OR
            (movement_type = 'OrderReservation'    AND on_hand_delta =  0 AND reserved_delta >  0) OR
            (movement_type = 'ReservationReleased' AND on_hand_delta =  0 AND reserved_delta <  0) OR
            (movement_type = 'Sale'                AND on_hand_delta <  0 AND reserved_delta <= 0) OR
            (movement_type = 'ManualDecrease'      AND on_hand_delta <  0 AND reserved_delta =  0) OR
            (movement_type = 'Damaged'             AND on_hand_delta <  0 AND reserved_delta =  0)
        ),

    -- Elle stok değişikliği gerekçesiz olamaz (denetlenebilirlik)
    CONSTRAINT chk_inventory_movements_manual_reason
        CHECK (
            movement_type NOT IN ('ManualIncrease','ManualDecrease','Damaged')
            OR (reason IS NOT NULL AND btrim(reason) <> '')
        ),

    -- Sipariş kaynaklı hareketler siparişe bağlı olmak zorunda.
    -- purchase_order_id zorunlu DEĞİL: siparişsiz mal alımı meşru bir senaryo.
    CONSTRAINT chk_inventory_movements_order_link
        CHECK (
            movement_type NOT IN ('Sale','OrderReservation','ReservationReleased')
            OR order_id IS NOT NULL
        )
);

CREATE INDEX ix_inventory_movements_variant_created
    ON inventory_movements (product_variant_id, created_at);
CREATE INDEX ix_inventory_movements_order_id
    ON inventory_movements (order_id);
CREATE INDEX ix_inventory_movements_purchase_order_id
    ON inventory_movements (purchase_order_id);
CREATE INDEX ix_inventory_movements_type_created
    ON inventory_movements (movement_type, created_at);
CREATE INDEX ix_inventory_movements_created_by
    ON inventory_movements (created_by_user_id);


-- ─────────────────────────────
-- 15) payment_plans
--     Bir siparişin ödeme mutabakatı — "zarf". Taksitlerin kendisi
--     installments (16) tablosunda yaşar; peşinat ayrı alan değil, özel taksittir.
--
--     NE ZAMAN OLUŞUR: sevkiyat anında (sipariş alındığında DEĞİL).
--     Mal gitmeden borç doğmaz; borç doğmadan plan kurmak anlamsızdır.
--     Sipariş iptal edilirse plan hiç oluşmamış olur — temizlenecek kayıt kalmaz.
--
--     V1'de sipariş başına TEK plan (katı 1:1). Plan revizyonu bilinçli olarak
--     ertelendi — zorluk şemada değil, "revize edilen plandaki taksite dağıtılmış
--     ödeme nereye gider?" sorusundadır.
-- ─────────────────────────────
CREATE TABLE payment_plans (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id              bigint        NOT NULL,

    created_by_user_id    bigint        NOT NULL,
    notes                 text          NULL,       -- mutabakat notu (plan seviyesinde)

    created_at            timestamptz   NOT NULL DEFAULT now(),
    -- Plan pasifleştirilmez (is_active yok) ama notes düzenlenebilir → updated_at var
    updated_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_payment_plans_order
        FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
    CONSTRAINT fk_payment_plans_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT
);

-- 1:1 — bir siparişin tek ödeme planı olur.
-- Revizyon gerekirse: WHERE status = 'Active' kısmi index'ine çevrilir (tek migration).
CREATE UNIQUE INDEX ux_payment_plans_order_id
    ON payment_plans (order_id);

CREATE INDEX ix_payment_plans_created_by
    ON payment_plans (created_by_user_id);


-- ─────────────────────────────
-- 16) installments
--     Ödeme planının satırları. Peşinat ayrı alan DEĞİL, installment_type
--     etiketi taşıyan sıradan bir taksittir.
--
--     status KOLONU YOKTUR — Ödendi/Kısmi/Bekliyor/Gecikmiş dördü de
--     SUM(payment_allocations) + due_date karşılaştırmasından türetilir.
--     'Gecikmiş' kimse bir şey yapmadan, sadece takvim ilerleyerek doğar;
--     saklanan bir kolon bunu ancak gece job'ıyla takip edebilirdi.
--
--     SİLİNEBİLİR (hard-delete yasağı listesinde bilinçli olarak yok):
--     niyet beyanıdır, olmuş olay değil. Ödeme dağıtılmışsa
--     payment_allocations'ın RESTRICT FK'si silmeyi zaten engeller.
-- ─────────────────────────────
CREATE TABLE installments (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_plan_id       bigint        NOT NULL,

    installment_number    smallint      NOT NULL,   -- plan içi sıra (1'den başlar)
    installment_type      varchar(20)   NOT NULL,   -- sadece etiket, para mantığı bakmaz

    amount                numeric(18,2) NOT NULL,
    due_date              date          NOT NULL,   -- saat anlamı yok → date

    notes                 text          NULL,

    created_at            timestamptz   NOT NULL DEFAULT now(),
    updated_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_installments_payment_plan
        FOREIGN KEY (payment_plan_id) REFERENCES payment_plans(id) ON DELETE RESTRICT,

    CONSTRAINT chk_installments_type
        CHECK (installment_type IN ('DownPayment', 'Regular')),
    CONSTRAINT chk_installments_amount_positive
        CHECK (amount > 0),
    CONSTRAINT chk_installments_number_positive
        CHECK (installment_number > 0)
);

-- Plan içinde sıra numarası tekrar edemez.
-- Bu index aynı zamanda payment_plan_id FK aramalarını da karşılar
-- (payment_plan_id baştaki kolon) → ayrı bir ix_..._payment_plan_id GEREKSİZ.
CREATE UNIQUE INDEX ux_installments_plan_number
    ON installments (payment_plan_id, installment_number);

-- Tahsilat panosunun ana index'i: "bu hafta vadesi gelenler", "gecikmişler".
CREATE INDEX ix_installments_due_date
    ON installments (due_date);


-- ─────────────────────────────
-- 17) payments
--     Perakendeciden FİİLEN ALINAN para. installments'ın karşıtı:
--     o "alınması gereken", bu "alınmış olan".
--
--     MÜŞTERİ SEVİYESİNDE yaşar, sipariş seviyesinde DEĞİL.
--     Müşteri "25.000 veriyorum" der, hangi taksitlere gideceğini söylemez —
--     dağıtımı sistem yapar (payment_allocations, Tablo 18).
--
--     TERS KAYIT: satır SİLİNMEZ, status = 'Reversed' işaretlenir.
--     Negatif tutarlı satır YOK — "eksi 50.000 tahsil ettik" diye bir olay
--     olmaz. Cari hesap düzeltmesi account_transactions'ta (Tablo 19) yapılır.
-- ─────────────────────────────
CREATE TABLE payments (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id           bigint        NOT NULL,

    amount                numeric(18,2) NOT NULL,
    payment_method        varchar(20)   NOT NULL,
    payment_date          date          NOT NULL,   -- paranın FİİLEN geldiği gün

    reference_no          varchar(100)  NULL,       -- dekont / çek no / makbuz no
    notes                 text          NULL,

    -- Ters kayıt (spec §8.4)
    status                varchar(20)   NOT NULL DEFAULT 'Active',
    reversed_at           timestamptz   NULL,
    reversed_by_user_id   bigint        NULL,
    reversal_reason       text          NULL,

    created_by_user_id    bigint        NOT NULL,
    created_at            timestamptz   NOT NULL DEFAULT now(),   -- SİSTEME giriş anı
    updated_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_payments_customer
        FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_payments_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_payments_reversed_by
        FOREIGN KEY (reversed_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,

    -- Negatif ödeme YASAK: iptalin tek yolu status='Reversed' olsun diye.
    -- İki farklı iptal yöntemi yan yana yaşarsa raporlar hangisini sayacağını bilemez.
    CONSTRAINT chk_payments_amount_positive
        CHECK (amount > 0),

    CONSTRAINT chk_payments_method
        CHECK (payment_method IN ('Cash', 'BankTransfer', 'CreditCard', 'Cheque', 'PromissoryNote')),

    CONSTRAINT chk_payments_status
        CHECK (status IN ('Active', 'Reversed')),

    -- İptal edilmiş kayıt, kim/ne zaman/neden bilgisi OLMADAN var olamaz.
    -- Aktif kayıtta bu üç alan da boş olmalı (yarım iptal diye bir şey yok).
    CONSTRAINT chk_payments_reversal_consistency
        CHECK (
            (status = 'Active'
                AND reversed_at IS NULL
                AND reversed_by_user_id IS NULL
                AND reversal_reason IS NULL)
            OR
            (status = 'Reversed'
                AND reversed_at IS NOT NULL
                AND reversed_by_user_id IS NOT NULL
                -- IS NOT NULL sart: btrim(NULL) <> '' sonucu NULL'dir ve CHECK,
                -- NULL sonucu GECERLI sayar -> guard olmadan gerekcesiz iptal gecerdi.
                AND reversal_reason IS NOT NULL
                AND btrim(reversal_reason) <> '')
        )
);

-- Spec'in istediği index: müşteri cari ekstresi, tarih aralığı raporu.
CREATE INDEX ix_payments_customer_date
    ON payments (customer_id, payment_date);

-- "Bugün ne kadar tahsilat yapıldı?" — müşteri ayrımı olmadan.
CREATE INDEX ix_payments_payment_date
    ON payments (payment_date);

CREATE INDEX ix_payments_created_by
    ON payments (created_by_user_id);

-- NOT: reference_no bilinçli olarak UNIQUE DEĞİLDİR — aynı dekont numarası iki
-- farklı bankada tekrarlanabilir, kullanıcı boş veya '-' bırakabilir.
-- Mükerrer tahsilat riski UI uyarısıyla çözülür (Faz 14).


-- ─────────────────────────────
-- 18) payment_allocations
--     payments ↔ installments köprüsü. Taşıyan (M:N + amount) ara tablo:
--     sadece "bağlı" değil, "NE KADARIYLA bağlı" bilgisini tutar.
--
--     Bir ödeme birden çok taksidi kapatabilir; bir taksit birden çok ödemeyle
--     kısmen kapanabilir. Dağıtımı sistem yapar: en eski vadesi geçmiş
--     taksitten başlayarak (spec §8.2).
--
--     status/is_reversed KOLONU YOKTUR — dağıtım kendi başına iptal edilmez,
--     bağlı olduğu ödeme iptal edilir. Sorgular
--     JOIN payments p ... AND p.status = 'Active' ile filtreler.
--     İkinci bir durum alanı iki doğruluk kaynağı yaratırdı.
--
--     SİLİNEBİLİR: para değil, paranın ATFI. "Dağıtımı Değiştir" eski
--     satırları silip yenilerini yazar; payments dokunulmaz kalır.
-- ─────────────────────────────
CREATE TABLE payment_allocations (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    payment_id            bigint        NOT NULL,
    installment_id        bigint        NOT NULL,

    amount                numeric(18,2) NOT NULL,

    created_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_payment_allocations_payment
        FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE RESTRICT,

    -- Bu RESTRICT, Tablo 16'da söz verilen korumadır:
    -- dağıtımı olan taksit SİLİNEMEZ. Uygulama kodu gerekmez.
    CONSTRAINT fk_payment_allocations_installment
        FOREIGN KEY (installment_id) REFERENCES installments(id) ON DELETE RESTRICT,

    CONSTRAINT chk_payment_allocations_amount_positive
        CHECK (amount > 0)
);

-- "Bu ödeme nereye dağıtıldı?" — ödeme detay ekranı
CREATE INDEX ix_payment_allocations_payment_id
    ON payment_allocations (payment_id);

-- "Bu taksit ne kadar ödendi?" — tahsilat panosunun sıcak sorgusu
CREATE INDEX ix_payment_allocations_installment_id
    ON payment_allocations (installment_id);

-- NOT: UNIQUE (payment_id, installment_id) bilinçli olarak YOKTUR.
-- UNIQUE, satır birleştirmeyi (UPDATE) zorunlu kılar; bu tablo bir defterdir
-- ve satırları güncellenmez. Gerçek koruma iki toplam kuralıdır ve onlar
-- çok satırlı olduğu için Application katmanındadır:
--   SUM(pa.amount WHERE payment_id = X)     <= payments[X].amount
--   SUM(pa.amount WHERE installment_id = Y) <= installments[Y].amount


-- ─────────────────────────────
-- 19) account_transactions
--     Perakendeci cari defteri. Müşteri bakiyesinin TEK doğruluk kaynağı.
--     customers.balance diye bir kolon YOKTUR ve olmayacaktır:
--       bakiye = SUM(amount)   (spec §8.5)
--
--     İŞARET KONVANSİYONU (kilitli):
--       amount > 0  →  müşterinin borcu ARTAR   (sipariş sevk edildi)
--       amount < 0  →  müşterinin borcu AZALIR  (tahsilat yapıldı)
--       Bakiye > 0  →  müşteri bize borçlu (normal durum)
--       Bakiye < 0  →  biz müşteriye borçluyuz (avans / fazla tahsilat)
--       Bakiye = 0  →  hesap kapalı
--
--     SAF APPEND-ONLY: UPDATE yok, DELETE yok, updated_at yok, status yok.
--     Ters kayıt = ters yönlü YENİ SATIR. (payments'taki 'Reversed'
--     işaretlemesinden farklı: orası fiziksel OLAY, burası MUHASEBE ETKİSİ.
--     "Eksi tahsilat" diye bir olay olmaz ama eksi defter satırı anlamlıdır.)
-- ─────────────────────────────
CREATE TABLE account_transactions (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id           bigint        NOT NULL,

    transaction_type      varchar(20)   NOT NULL,
    amount                numeric(18,2) NOT NULL,   -- işaretli

    -- Kaynak belge (tipine göre biri dolu olur)
    order_id              bigint        NULL,
    payment_id            bigint        NULL,

    description           text          NULL,

    created_by_user_id    bigint        NOT NULL,
    created_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_account_transactions_customer
        FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_account_transactions_order
        FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT,
    CONSTRAINT fk_account_transactions_payment
        FOREIGN KEY (payment_id) REFERENCES payments(id) ON DELETE RESTRICT,
    CONSTRAINT fk_account_transactions_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,

    -- Sıfır tutarlı defter satırı gürültüdür.
    CONSTRAINT chk_account_transactions_amount_nonzero
        CHECK (amount <> 0),

    -- Tip ↔ işaret ↔ kaynak belge imzası.
    -- inventory_movements.chk_..._type_signature'ın finans karşılığı:
    -- geçerli tip listesini de zorlar (listede olmayan tip hiçbir dala uymaz).
    CONSTRAINT chk_account_transactions_type_signature
        CHECK (
            -- Sipariş sevkiyatı: borç artar, siparişe bağlı olmak ZORUNDA
            (transaction_type = 'Sale'
                AND amount > 0
                AND order_id IS NOT NULL AND payment_id IS NULL)
            OR
            -- Tahsilat: borç azalır, ödemeye bağlı olmak ZORUNDA
            (transaction_type = 'Payment'
                AND amount < 0
                AND payment_id IS NOT NULL AND order_id IS NULL)
            OR
            -- Ters kayıt: işaret serbest (neyi ters çevirdiğine bağlı),
            -- ama bir kaynağa bağlı olmak zorunda
            (transaction_type = 'Reversal'
                AND (order_id IS NOT NULL OR payment_id IS NOT NULL))
            OR
            -- Manuel düzeltme: kaynak belgesi olmayabilir, ama açıklama ZORUNLU.
            -- IS NOT NULL şart: btrim(NULL) <> '' sonucu NULL'dır ve CHECK,
            -- NULL sonucu GEÇERLİ sayar → guard olmadan gerekçesiz satır geçerdi.
            (transaction_type = 'Adjustment'
                AND description IS NOT NULL
                AND btrim(description) <> '')
        )
);

-- Cari ekstre sorgusunun index'i (spec'in istediği):
-- "Bu müşterinin hareketleri, tarih sırasıyla"
CREATE INDEX ix_account_transactions_customer_created
    ON account_transactions (customer_id, created_at);

CREATE INDEX ix_account_transactions_order_id
    ON account_transactions (order_id);
CREATE INDEX ix_account_transactions_payment_id
    ON account_transactions (payment_id);
CREATE INDEX ix_account_transactions_created_by
    ON account_transactions (created_by_user_id);

-- NOT: balance_after (yürüyen bakiye) kolonu YOKTUR. Saklanan türetilmiş
-- değerdir: araya geriye dönük bir satır girerse sonraki tüm satırlar
-- yanlışlanır. Ekstre ekranı SUM(amount) OVER (ORDER BY created_at, id)
-- pencere fonksiyonuyla anlık hesaplar.


-- ─────────────────────────────
-- 20) supplier_payments
--     Üreticiye YAPTIĞIMIZ ödemeler. payments'ın üretici aynası.
--
--     ASİMETRİ (spec §8.3, bilinçli): üretici tarafında taksit planı, taksit
--     ve dağıtım tablosu YOKTUR. Vadeyi üretici koyar
--     (purchase_orders.payment_due_date), biz ne ödediğimizi kaydederiz.
--     Kontrolü bizde olmayan bir süreci detaylı modellemek anlamsızdır.
--     Gereksiz simetri kurmak da bir over-engineering biçimidir.
--
--     payments'tan TEK YAPISAL FARK: purchase_order_id kolonu var.
--     Ödeme yaparken hangi faturayı kapattığımızı biliriz — ama toplu ödeme
--     ve avans senaryoları için nullable bırakıldı.
--
--     🔴 GİZLİLİK: bu tablo üreticiye ASLA açılmaz. Ödeme tarihlerimizi
--     görmesi nakit akışımızı ve pazarlık gücümüzü ele verir. Faz 18'de
--     Manufacturer rolüne bu tablo için hiçbir endpoint yok → 403.
--
--     Ters kayıt deseni payments ile BİREBİR AYNI (kasıtlı tutarlılık).
-- ─────────────────────────────
CREATE TABLE supplier_payments (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id           bigint        NOT NULL,

    -- Hangi faturayı kapatıyor? Toplu ödeme/avansta NULL.
    purchase_order_id     bigint        NULL,

    amount                numeric(18,2) NOT NULL,
    payment_method        varchar(20)   NOT NULL,
    payment_date          date          NOT NULL,   -- paranın FİİLEN çıktığı gün

    reference_no          varchar(100)  NULL,       -- dekont / çek no
    notes                 text          NULL,

    -- Ters kayıt (spec §8.4) — payments ile aynı desen
    status                varchar(20)   NOT NULL DEFAULT 'Active',
    reversed_at           timestamptz   NULL,
    reversed_by_user_id   bigint        NULL,
    reversal_reason       text          NULL,

    created_by_user_id    bigint        NOT NULL,
    created_at            timestamptz   NOT NULL DEFAULT now(),
    updated_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_supplier_payments_supplier
        FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_supplier_payments_purchase_order
        FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE RESTRICT,
    CONSTRAINT fk_supplier_payments_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_supplier_payments_reversed_by
        FOREIGN KEY (reversed_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,

    CONSTRAINT chk_supplier_payments_amount_positive
        CHECK (amount > 0),

    CONSTRAINT chk_supplier_payments_method
        CHECK (payment_method IN ('Cash', 'BankTransfer', 'CreditCard', 'Cheque', 'PromissoryNote')),

    CONSTRAINT chk_supplier_payments_status
        CHECK (status IN ('Active', 'Reversed')),

    CONSTRAINT chk_supplier_payments_reversal_consistency
        CHECK (
            (status = 'Active'
                AND reversed_at IS NULL
                AND reversed_by_user_id IS NULL
                AND reversal_reason IS NULL)
            OR
            (status = 'Reversed'
                AND reversed_at IS NOT NULL
                AND reversed_by_user_id IS NOT NULL
                -- IS NOT NULL sart: btrim(NULL) <> '' sonucu NULL'dir ve CHECK,
                -- NULL sonucu GECERLI sayar -> guard olmadan gerekcesiz iptal gecerdi.
                AND reversal_reason IS NOT NULL
                AND btrim(reversal_reason) <> '')
        )
);

-- Üretici cari ekstresi, tarih aralığı raporu
CREATE INDEX ix_supplier_payments_supplier_date
    ON supplier_payments (supplier_id, payment_date);

-- "Bu satın alma siparişine ne kadar ödedik?"
CREATE INDEX ix_supplier_payments_purchase_order_id
    ON supplier_payments (purchase_order_id);

-- Nakit akışı: "bu ay ne kadar para çıktı?"
CREATE INDEX ix_supplier_payments_payment_date
    ON supplier_payments (payment_date);

CREATE INDEX ix_supplier_payments_created_by
    ON supplier_payments (created_by_user_id);

-- NOT: supplier_payment_allocations diye bir tablo YOKTUR (spec §8.3).
-- Toplu ödeme faturalara dağıtılmaz, yalnızca bakiyeyi azaltır.


-- ─────────────────────────────
-- 21) supplier_transactions
--     Üretici cari defteri. account_transactions'ın aynası.
--     suppliers.balance diye bir kolon YOKTUR:  bakiye = SUM(amount)
--
--     🔴 İŞARET KONVANSİYONU — account_transactions'ın TERS PERSPEKTİFİ:
--       amount > 0  →  BİZİM BORCUMUZ ARTAR   (mal kabul edildi)
--       amount < 0  →  BİZİM BORCUMUZ AZALIR  (ödeme yaptık)
--       Bakiye > 0  →  üreticiye borçluyuz (normal durum)
--       Bakiye < 0  →  üretici bize borçlu (avans / fazla ödeme)
--       Bakiye = 0  →  hesap kapalı
--
--     Her iki defterde de "bakiye pozitif = borç var" okunur; yalnızca
--     borçlunun kim olduğu tabloya göre değişir. Bu kasıtlıdır — ekranda
--     eksi rakamı "borç" diye okumak zorunda kalmamak için.
--
--     🔑 Purchase, sipariş VERİLDİĞİNDE değil MAL KABUL EDİLDİĞİNDE doğar.
--     (Sale'in sevkiyatta doğmasının simetriği: mal gelmeden borç doğmaz.)
--     Kısmi mal kabul → her parti kendi Purchase satırını yazar; böylece
--     gelmemiş malın parası borç olarak görünmez.
--
--     🔴 GİZLİLİK: üretici bu defteri göremez. Bakiyesini görebilir (tek bir
--     SUM olarak), defterin kendisini değil. Her sorgu token'daki supplier_id
--     ile filtrelenir — invariant #2.
--
--     SAF APPEND-ONLY: UPDATE yok, DELETE yok, updated_at yok, status yok.
--     Ters kayıt = ters yönlü YENİ SATIR.
-- ─────────────────────────────
CREATE TABLE supplier_transactions (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id           bigint        NOT NULL,

    transaction_type      varchar(20)   NOT NULL,
    amount                numeric(18,2) NOT NULL,   -- işaretli

    -- Kaynak belge (tipine göre biri dolu olur)
    purchase_order_id     bigint        NULL,
    supplier_payment_id   bigint        NULL,

    description           text          NULL,

    created_by_user_id    bigint        NOT NULL,
    created_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_supplier_transactions_supplier
        FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,
    CONSTRAINT fk_supplier_transactions_purchase_order
        FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE RESTRICT,
    CONSTRAINT fk_supplier_transactions_payment
        FOREIGN KEY (supplier_payment_id) REFERENCES supplier_payments(id) ON DELETE RESTRICT,
    CONSTRAINT fk_supplier_transactions_created_by
        FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE RESTRICT,

    CONSTRAINT chk_supplier_transactions_amount_nonzero
        CHECK (amount <> 0),

    CONSTRAINT chk_supplier_transactions_type_signature
        CHECK (
            -- Mal kabul: borcumuz artar, satın alma siparişine bağlı ZORUNLU
            (transaction_type = 'Purchase'
                AND amount > 0
                AND purchase_order_id IS NOT NULL AND supplier_payment_id IS NULL)
            OR
            -- Ödeme: borcumuz azalır, ödeme kaydına bağlı ZORUNLU.
            -- purchase_order_id BURADA da dolu olabilir: faturaya bağlı ödemede
            -- defterde de görünmesi ekstreyi okunur kılar. (account_transactions'ta
            -- Payment için order_id IS NULL zorlanıyordu — aynalamanın bilinçli
            -- olarak kırıldığı tek nokta; iş akışı gerçekten farklı.)
            (transaction_type = 'Payment'
                AND amount < 0
                AND supplier_payment_id IS NOT NULL)
            OR
            -- Ters kayıt: işaret serbest, bir kaynağa bağlı olmak zorunda
            (transaction_type = 'Reversal'
                AND (purchase_order_id IS NOT NULL OR supplier_payment_id IS NOT NULL))
            OR
            -- Manuel düzeltme: kaynak belgesi olmayabilir, açıklama ZORUNLU
            -- (siparişsiz mal alımı buraya düşer).
            -- IS NOT NULL şart: btrim(NULL) <> '' sonucu NULL'dır ve CHECK,
            -- NULL sonucu GEÇERLİ sayar → guard olmadan gerekçesiz satır geçerdi.
            (transaction_type = 'Adjustment'
                AND description IS NOT NULL
                AND btrim(description) <> '')
        )
);

-- Üretici cari ekstresi (spec'in istediği index)
CREATE INDEX ix_supplier_transactions_supplier_created
    ON supplier_transactions (supplier_id, created_at);

CREATE INDEX ix_supplier_transactions_purchase_order_id
    ON supplier_transactions (purchase_order_id);
CREATE INDEX ix_supplier_transactions_payment_id
    ON supplier_transactions (supplier_payment_id);
CREATE INDEX ix_supplier_transactions_created_by
    ON supplier_transactions (created_by_user_id);


-- ─────────────────────────────
-- 22) audit_logs
--     Sistem geneli denetim kaydı. order_history bir ÖZELLİK'tir (kullanıcı
--     "siparişim ne oldu?" diye bakar); bu bir KONTROL'dür (denetçi "kim ne
--     yaptı?" diye bakar). Örtüşme normaldir ve sorun değildir.
--
--     🔑 POLİMORFİK REFERANS: entity_id bir FK DEĞİLDİR ve olamaz —
--     bu tablo 21 tablonun hepsine referans verebilmeli. Bedeli bilinçli
--     olarak kabul edildi çünkü:
--       (1) buraya yalnızca sistem yazar (kullanıcı elle giremez),
--       (2) denetim kaydı denetlediği şeyden DAHA UZUN yaşamalıdır:
--           silinen bir kaydın izi silinmemeli (CASCADE yanlış olurdu),
--           silme de engellenmemeli (RESTRICT yanlış olurdu).
--
--     entity_type'a CHECK konmadı: yeni tablo eklendiğinde migration
--     gerekmesin diye. Değerler C# tarafında nameof() sabitlerinden gelir.
--     Aynı gerekçe action için de geçerli.
--
--     🔴 ASLA LOGLANMAZ (spec §13): password_hash, token, secret,
--     connection_string. DB bunu zorlayamaz (JSONB serbest yapıdır) —
--     Application katmanındaki AuditService'te SABİT KARA LİSTE ile uygulanır.
--
--     SAF APPEND-ONLY: UPDATE yok, DELETE yok, updated_at yok.
--     Değiştirilebilen bir denetim kaydı denetim değildir.
-- ─────────────────────────────
CREATE TABLE audit_logs (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Kim (NULL = başarısız giriş denemesi veya sistem işlemi)
    user_id               bigint        NULL,

    -- Ne yaptı
    action                varchar(50)   NOT NULL,   -- 'Create','Update','Delete','Login',...

    -- Neye yaptı (polimorfik — entity_id FK DEĞİL)
    entity_type           varchar(100)  NOT NULL,   -- 'Order','Product','Payment',...
    entity_id             bigint        NULL,       -- Login gibi hedefsiz olaylarda NULL

    -- Ne değişti (YALNIZCA değişen alanlar; tüm satır iki kez saklanmaz)
    old_values            jsonb         NULL,
    new_values            jsonb         NULL,

    description           text          NULL,       -- insan-okunur özet

    -- Nereden (Aşama 2 / VPS için kritik)
    -- inet yerine varchar(45): EF Core eşlemesi basit kalsın, alt ağ sorgusu
    -- yapılmayacak. 45 = IPv4-eşlemeli IPv6'nın tam uzunluğu.
    ip_address            varchar(45)   NULL,

    created_at            timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT fk_audit_logs_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,

    CONSTRAINT chk_audit_logs_action_not_blank
        CHECK (btrim(action) <> ''),
    CONSTRAINT chk_audit_logs_entity_type_not_blank
        CHECK (btrim(entity_type) <> '')
);

-- Spec'in istediği index: "Bu kayda kim ne yaptı?" — denetim ekranının ana sorgusu
CREATE INDEX ix_audit_logs_entity
    ON audit_logs (entity_type, entity_id);

-- "Bu kullanıcı bugün ne yaptı?"
CREATE INDEX ix_audit_logs_user_created
    ON audit_logs (user_id, created_at);

-- "Son 24 saatte sistemde ne oldu?" — kronolojik tarama
CREATE INDEX ix_audit_logs_created_at
    ON audit_logs (created_at);

-- NOT (Faz 20): bu, sistemdeki en hızlı büyüyen tablo olacak (~70.000 satır/yıl).
-- Saklama politikası (süresiz / arşiv tablosu / partition) Faz 20'de kararlaştırılacak.
-- Veri yokken ölçmeden optimize etmek erken olur.


-- ============================================================
--  22/22 TABLO TAMAMLANDI
-- ============================================================
